### ISSUE TITLE
Issue #1 - User can send a file (capsule) to the server.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#1]
## 💰 Feature

User can send a file to the server.

## 🗒️ Notes

This will require me to create the basic structure of the app, create a form for users to upload files, and add functionality to upload those files to an AWS S3 bucket.
Will require learning drag and drop functionality.

## 🖼 Wireframe

<img width="359" alt="Screen Shot 2020-12-28 at 10 47 30 AM" src="https://user-images.githubusercontent.com/71002706/103236598-2386e900-48fa-11eb-93ba-651ae60e8cbf.png">

## ✅ Tasks

- [x]  Install all included dependencies. Also install React Bulma.
- [x] Make a copy of the '.env.example' and name it '.env'.
- [x] Create a components folder in the client directory.
- [x] Create a file named navbar.jsx.
- [x] Within navbar.jsx, create a React Component for a NavBar with placeholder text.
- [x] Alter the app.jsx file to render the navbar before the home view.
- [x] Build a proper navbar.
- [x] Import fonts.
- [x] Add style to the navbar.
- [x] Create a new .jsx file in the pages folder for the capsule creation form.
- [x] Make a quick placeholder capsule entry view.
- [x] Insert the newly created view into the app.jsx file where its currently rendering the home view.
- [x] Create a file in the components folder, and name it capsule-creation-form.jsx.
- [x] Create a react component within capsule-creation-form.jsx that renders a quick placeholder form.
- [x] Alter the render method of capsule-creation-view.jsx to render the newly created component.
- [x] Start building out the real component, starting with the form background (container).
- [x] Create the first field in the form, 'upload your files here'.
- [x] Add styling.
- [x] Create the upload button.
- [x] Add styling.
- [x] Create a submit button.
- [x] Add styling.
- [x] Give the current form a final polish.
- [x] Add test file to be sent when a user clicks the submit button on the form. (To test the uploads)
- [x] Add an onSubmit prop to the form.
- [x] Create a handleSubmit function to be called when the form is submitted.
- [x]  Add a constructor method to the CapsuleCreationForm component.
- [x] Install the aws-sdk as a dependency.
- [x] Set up a basic post route in index.js.
- [x] Configure the the CapsuleCreationForm onSubmit handler to send a post request to the server.
- [x] Install multer-s3 as a dependency.
- [x] Add bucket info and credentials to the .env file.
- [x] Expand the post route to send a file to the S3 bucket. Verify S3 receives this file.
- [x] Add JSON middleware to index.js.
- [x] Create a state for the CapsuleCreationForm to hold the file name.
- [x] Expand the post request in the CapsuleCreationForm to send the test file in its request body.
- [x] Use the fileName property of the request body as the file to upload to S3 in the post route of index.js.
- [x] Test that the bucket is receiving this file correctly.
- [x] Replace the upload button with an input of type file.
- [x] Create an uploads-middleware file in the server folder.
- [x] Install multer as a dependency. (needed for multer-s3)
- [x] Enhance the handleSubmit function to send the file in it's request body.
- [x] Enhance the server's post route to upload the file sent in the request body to the S3 bucket.
- [x] Remove uploads-middleware.js (didn't need it).
- [x] Remove the test file.
- [x] Test that the user can successfully upload their own files to the bucket.
- [x] Add an onDrop and onDragOver prop to the drag-drop-field.
- [x] Create onDrop and onDragover handler functions and bind them to this.
- [x] Expand the handleDrop function to store the dropped file in a variable, file.
- [x] Create a Ref named fileInput and put it in the constructor.
- [x] Add the Ref to the input element.
- [x] Adjust the handleDrop function to use the newly created Ref.
- [x] Change drag-drop-field to drop-zone.
- [x] Add an onClick prop to the drop-zone.
- [x] Create a function for the onClick prop named handleClick.
- [x] Bind handleClick to this.
- [x]  Enhance the handleClick function to 'click' the fileInput ref and open the users file browser.
- [x] Add an onChange prop to the file input.
- [x] Make a function for the onChange prop.
- [x] Enhance the function to store the value file name in state.
- [x] Make the name appear inside the drop-zone when a file is selected.
- [x] Adjust the onDrop function to set state with a new fileName when a file is dropped.
- [x] Add style to make it look neat.
- [x] Make the fileInput hidden.
- [x] BUG: state should refresh after a file is submitted.
- [x] Test, kill bugs, polish.

Revisions

- [x] Update .env.example with dummy AWS credentials.
- [x] Set a height for the drop zone so that it doesn't suddenly change height when the text content changes.
- [x]  Remove the unused middleman component CapsuleCreationView.
- [x] Remove react-bulma-components from dependencies.
