### ISSUE TITLE
Issue #6 - User can Sign In/ Sign Up/ Sign Out

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#11]
## 💰 Feature

User can Sign In/ Sign Up/ and Sign Out.

## 🗒️ Notes

This will require me to set up all routes and middleware to handle user registration, authentication, and authorization. Then I'll need to create two home pages. One for users who are not authenticated, and one for users who are.

## 🖼 Wireframe
<img width="339" alt="Screen Shot 2021-01-04 at 10 29 00 PM" src="https://user-images.githubusercontent.com/71002706/103613911-4c037a00-4edc-11eb-9421-c48e9db29ec5.png">

## ✅ Tasks

---BACK END---

--Registration--

- [x] Expand the users table in the db to have a username column with text values that are NOT NULL and a hashedPassword column with text values that are NOT NULL.
- [x] Add jsonMiddleware.
- [x] Create a post route for signing-up that console.logs the values of username and password.
- [x] Add an if statement checking if username and password have been entered (if not, respond with an error 400).
- [x] Require argon2, then revise the post route to hash the users password and console.log it.
- [x] Revise the route to THEN query the db and insert the username and hashedPassword into the users table, returning the userId and username columns.

--Authentication--

- [x] Create a post route for api/auth/sign-in.
- [x] Check that both username and passwords are not undefined.
- [x] Create the sql and params variables, then query the db and select the userId and hashedPassword from the users table where the username is equal to the entered username
- [x] Then, check result.rows to see if that the username exists in the db. If not, send an error.
- [x] Using argon2.verify, confirm that the passwords are matching.
- [x] Then check if the password and the hashedPassword are matching. If not, send an error(401).
- [x] Require jsonwebtoken.
- [x] Send a json object containing the token and payload.

BUG: Responses are being sent more than once. FIX: change all the res.json to throw a 'client error'.

- [x] Create two files, client-error.js and error-middleware.js.
- [x] Build out the files as shown in api-authorization.
- [x] Require client-error.js and error-middleware.js and add a use route for the errorMiddleware.
- [x] Instead of using res.json(), throw a new ClientError.

--Authorization--

- [x] Create a file named authorization-middleware.js and build it, referencing the code in api-authentication.
- [x] Require authorization-middleware.js and assign it to a variable, authorizationMiddleware.
- [x] Tell the app to use authorizationMiddleware before the post route at api/uploads
- [x] Thoroughly test the back end.

---FRONT END---
- [x] Create the Figma for the login page.
- [x] Create a file in the components folder names sign-in-sign-up-form.jsx
- [x] Create a React component for the sign-in/sign-up form.
- [x] Tweak the app.jsx file to show the new component.
- [x] Expand the component into a proper form.
- [x] Add style, make it look decent.
- [x] Add an onClick prop to the sign-up button. 
- [x] Create a basic function, handleSignUpClick, that is called when the user clicks the Sign Up button.
- [x] Add an onClick prop to the Sign In button.
- [x] Create a basic function, handleSignInClick
- [x] Scrap the handleClick functions; Define a handleSubmit function instead.
- [x] Add onChange props to the username and password inputs.
- [x] Create basic functions, handleUsernameChange and handlePasswordChange.
- [x] Add value props to the username and password inputs.
- [x] Create a state for the form to hold the username and password values.
- [x] Configure the handleUsernameChange function to assign the current value of the username input to state.
- [x] Configure the handlePasswordChange function to assign the current value of the password input to state.
- [x] Expand the handleSubmit function to fetch a post request to the server at api/auth/sign-up using the stringified state.

User can sign up completed

Add hash routing.
- [x] Add a lib folder with one file, parse-route.js.
- [x] Build out the file, referencing react-hash-routing.
- [x] Add a state for route to the App Component.
- [x] Add a componentDidMount method to the App Component.
- [x] Inside the componentDidMount method, listen for hash change events on the window object.
- [x] Configure the method so that each time the window.location.hash changes, parse it with parseRoute() and update state.
- [x] Add an onClick event listener to each button that changes the hash to something relevant.

Hash Routing completed.

- [x] Create some context, including user, route, and two functions, handleSignIn, and handleSignOut.
- [x] Adjust the handleSubmit event to check the route context, and then send a post request to sign up if a user clicks the sign-up button.
- [x] Expand the handleSubmit method to send a post request to sign in if a user clicks the sign-in button.

Create a landing page for users who are authenticated and enable 'page' swapping

- [x] Add a renderPage method that looks at the current state of the window to decide what to show in the app.
- [x] Clean up the handleSubmit method by removing the if/else and using template literals to specify action.
- [x] Configure the app to open an empty view (the new landing page) when the user successfully logs in.
- [x] Verify that a token is saved to local storage to id users.
- [x] Test that a user does not have to sign in again if they are already validated.

User can Sign In (and stay signed in) completed.

- [x] Add a button on the navbar that will sign a user out and return them to the login page.
- [x] Make the navbar look neat.

Make the capsule tied to the sender's userId

- [x] In the handleSubmit of the CapsuleCreationForm, get the token from localStorage and assign it to the 'x-access-token' property of the headers in req.
- [x] Create a variable 'userId', by destructuring req.user.
- [x] Configure the SQL in the post route to insert the userId of the sender on submission.
- [x] Make it so that when a user clicks sign-up, they are automatically signed in.

- [x] Test, polish, kill all bugs.
