### ISSUE TITLE
Issue #7 - Users can view their pending capsules

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#12]
## 💰 Feature

Users can view their pending capsules.

## 🗒️ Notes

This will require me to set up a get route in the back end which returns all capsules tied to a specific user, and then create a page where all capsules will be neatly visible, ordered from the soonest sendAt time to latest.

## 🖼 Wireframe
<img width="361" alt="Screen Shot 2021-01-06 at 1 16 23 PM" src="https://user-images.githubusercontent.com/71002706/103820545-66933b80-5021-11eb-9e24-28eca78efe91.png">

## ✅ Tasks
Back end
--

- [x] Create a get route in index.js 
- [x] Enhance the route to query the db for ALL capsules.
- [x] Enhance the db query to select only the capsules tied the the active user.
- [x] Thoroughly test back end.

Front end
--

- [x] Create a 'Create' button in the Home Component.
- [x] Add an onClick prop to the button with an event listener to change the window.location.hash to create.
- [x] Create a component named CapsuleList.
- [x] Enhance the component to fetch a response from the server for all capsules tied to the user.
- [x] Enhance the CapsuleList component to render each capsule after receiving the response.

Test, LOTS of polish, kill all bugs.
--
- [x] Make the create button look nice.
- [x] Make the user's list of capsules look good.
- [x] Add a home button (or icon) to the navbar.
- [x] Make each individual capsule look good.
- [x] Convert the time into something more approachable to the average user, then add it to the capsule.
- [x] Thoroughly test EVERYTHING. Document any unintended functionality.
