### ISSUE TITLE
Issue #8 - User can download the contents of a capsule.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#13]
## 💰 Feature

User can download the contents of a capsule.

## 🗒️ Notes

For this, I'll need to alter the download link in the sent email to point to a route on my own server. That route will use the S3 SDK to generate a temporary s3 download link for the file and redirect the recipient there. Will need to add a .env variable to swap out localhost or Heroku.

## ✅ Tasks

Back end
-

- [x] Create a public get route at /api/link.
- [x] Enhance this route to generate a temporary S3 download link with getSignedUrlPromise.
- [x] Respond with the a redirect to the url.
- [x] Tweak the route to take the key value from the request.
- [x] Add an .env variable to swap between localhost and Heroku in the email link to the get route.

Front end
--

- [x] Tweak the download link in send-emails.js to point to the new route.
- [x] Test, polish, kill all bugs.
