### ISSUE TITLE
Issue # 2 - User can add a recipient for the capsule

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#3]
## 💰 Feature

User can add a recipient for the capsule.

## 🗒️ Notes

This will require me to add a field to the form for the recipient, and create a database to store the created capsule, including the files download url from the S3 bucket.

## 🖼 Wireframe
<img width="358" alt="Screen Shot 2020-12-30 at 11 08 01 AM" src="https://user-images.githubusercontent.com/71002706/103375534-4f87a300-4a8f-11eb-827a-eda4d9b19ae2.png">

## ✅ Tasks

Front end.
- [x] Remove the encasing div and styling from the hidden input element. (Because it's hidden, duh)
- [x] Expand the form to include a field for the recipient.
- [x] Add style.

Back end
- [x] Verify that the recipient data from the form is being received correctly.
- [x] Create the database
- [x] Query the db to insert the capsule's recipient into the db on post routes.
- [x] Find a way to get the download url from the S3 bucket.
- [x] Adjust the db query to also insert the capsule download url using req.file.location.
- [x] Test, polish, kill all bugs.
