### ISSUE TITLE
Issue #12 - Final pre-portfolio revisions.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#31]
## 💰 Feature

Make the app look professional.

## 🗒️ Notes

<img width="951" alt="Screen Shot 2021-01-20 at 5 56 34 PM" src="https://user-images.githubusercontent.com/71002706/105269475-d7217880-5b48-11eb-9b92-a9ac76bfc55c.png">

## ✅ Tasks

- [x] Change 'Create' to 'Create a new capsule'.
- [x] Change 'Submit' to 'Seal the time capsule'.
- [x] Change 'Send' to 'Sent' if the send time is in the past.
##### Add a 'hook' to the landing page: a description (with visuals) of what the app is, why the user might benefit from using it, and a quick demo of the steps necessary to use it (minus any account creation).
- [x] Create a new component, Hook, which will be rendered under the Auth Page.
- [x] Fill it out with proper info.
- [x] Make it look nice.
- [x] Final testing and polish.
