### ISSUE TITLE
Issue #3 - User can receive a capsule

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#5]
## 💰 Feature

User can receive a capsule.

## 🗒️ Notes

This will require me to set up nodeMailer in my server code, and configure my post route to send an email to the recipient.
## ✅ Tasks
- [x] Install nodemailer as a dependency.
- [x] Require the nodemailer package and assign it to a variable, nodemailer.
- [x] Create the transporter object using nodemailer.createTransport()
- [x] Inside the post route, send an email using transporter.sendMail with some test data.
- [x] Configure the sendMail method call to send the test file to the proper recipient.
- [x] Add a link to the file download in the email body.

Make the email look halfway decent.

- [x] Build out the header of the email.
- [x] Build out the download section of the email.
- [x] Add text below download section.
- [x] Test, polish, kill all bugs.
