### ISSUE TITLE
Issue #4 - User can specify the date and time for each capsule.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#7]
## 💰 Feature

User can specify the time and date for the capsule to be sent.

## 🗒️ Notes

This will require me to create a section on my form for time and date, and verify that those values are being correctly stored in my database when a user clicks submit.

## 🖼 Wireframe
<img width="359" alt="Screen Shot 2020-12-28 at 10 47 30 " src="https://user-images.githubusercontent.com/71002706/103431855-c3a77100-4b8b-11eb-8f2b-8acb552e768e.png">

## ✅ Tasks

- [x] Expand the form to include a section for the date.
- [x] Expand the form to include a section for the time.
- [x] Add style.
- [x] Add jsonMiddleware.
- [x] Create a new date object containing all relevant data and stringify it.
- [x] Remove jsonMiddleware (didn't need it).
- [x] Adjust the db query to insert the date for each capsule.
- [x] Verify that the correct values are being sent to the server.
- [x] Test, polish, kill all bugs.
