### ISSUE TITLE
Issue #5 - User can receive a scheduled capsule

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/time-capsule#9]
## 💰 Feature

User can receive a scheduled capsule.

## 🗒️ Notes

This will require me to create a file in my server directory that can query the database, get the unsent capsules that precede the current time, and send your email.

## ✅ Tasks

- [x] In the db, change send to sendOn.
- [x] Adjust the db query in index.js to reflect changes.
- [x] In the db, add a column sentAt as a timestamp.
- [x] Create a file in your server directory named send-emails.js.
- [x] In send-emails.js, query the database to SELECT the recipient and content FROM capsules table.
- [x] Expand the query to select WHERE sendOn is before the current time.
- [x] Require nodemailer.
- [x] Create a transporter object.
- [x] After the query, THEN send emails.
- [x] After emails are sent, THEN update sentAt column of the db.
- [x] Deploy app on Heroku.
- [x] Set up Heroku scheduled jobs.
- [x] Remove the mailing functionality in index.js (so that emails aren't instantly sent when a user submits).
- [x] Test, polish, kill all bugs.
- [x] Use an .env variable for the sendMail method call.
- [x] Instead of throwing errors, use console.error(error)
- [x] Change the for loop to keep res.rows as an object and access properties.
- [x] Test, polish, kill all bugs.
